--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY test IS
PORT(
  entree	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
  shift_val	: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
  sortie	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0)
);
END test;

ARCHITECTURE RTL OF test IS
  SIGNAL rtl_std_logic_vector_4	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL rtl_std_logic_vector_3	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL rtl_std_logic_vector_2	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL rtl_std_logic_vector_1	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL rtl_std_logic_vector_0	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL etg1_s	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL etg2_s	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL etg3_s	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL etg4_s	: STD_LOGIC_VECTOR(31 DOWNTO 0);
BEGIN
  rtl_std_logic_vector_4 <= (entree(30 downto 0) & '0');
  rtl_std_logic_vector_3 <= (etg1_s(29 downto 0) & "00");
  rtl_std_logic_vector_2 <= (etg2_s(27 downto 0) & "0000");
  rtl_std_logic_vector_1 <= (etg3_s(23 downto 0) & "00000000");
  rtl_std_logic_vector_0 <= (etg4_s(15 downto 0) & "0000000000000000");
  sortie <= rtl_std_logic_vector_0 WHEN (shift_val(4) = '1') ELSE
     etg4_s;
  etg4_s <= rtl_std_logic_vector_1 WHEN (shift_val(3) = '1') ELSE
     etg3_s;
  etg3_s <= rtl_std_logic_vector_2 WHEN (shift_val(2) = '1') ELSE
     etg2_s;
  etg2_s <= rtl_std_logic_vector_3 WHEN (shift_val(1) = '1') ELSE
     etg1_s;
  etg1_s <= rtl_std_logic_vector_4 WHEN (shift_val(0) = '1') ELSE
     entree;
END RTL;
