--
-- Generated by VASY
--
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY shifter IS
PORT(
  shift_lsl	: IN STD_LOGIC;
  shift_lsr	: IN STD_LOGIC;
  shift_asr	: IN STD_LOGIC;
  shift_ror	: IN STD_LOGIC;
  shift_rrx	: IN STD_LOGIC;
  shift_val	: IN STD_LOGIC_VECTOR(4 DOWNTO 0);
  din	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);
  cin	: IN STD_LOGIC;
  dout	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
  cout	: OUT STD_LOGIC;
  vdd	: IN BIT;
  vss	: IN BIT
);
END shifter;

ARCHITECTURE RTL OF shifter IS
  SIGNAL rtl_unsigned_13	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_12	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_11	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_10	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_9	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_8	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_7	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_6	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_5	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_4	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_3	: UNSIGNED(30 DOWNTO 0);
  SIGNAL rtl_unsigned_2	: UNSIGNED(4 DOWNTO 0);
  SIGNAL rtl_signed_1	: SIGNED(30 DOWNTO 0);
  SIGNAL rtl_std_logic_vector_0	: STD_LOGIC_VECTOR(30 DOWNTO 0);
  SIGNAL rtlexts_1	: SIGNED(30 DOWNTO 0);
  SIGNAL rtlexts_0	: UNSIGNED(4 DOWNTO 0);
  SIGNAL rtldef_68	: STD_LOGIC;
  SIGNAL rtldef_67	: STD_LOGIC;
  SIGNAL rtldef_66	: STD_LOGIC;
  SIGNAL rtldef_65	: STD_LOGIC;
  SIGNAL rtldef_64	: STD_LOGIC;
  SIGNAL rtldef_63	: STD_LOGIC;
  SIGNAL rtldef_62	: STD_LOGIC;
  SIGNAL rtldef_61	: STD_LOGIC;
  SIGNAL rtldef_60	: STD_LOGIC;
  SIGNAL rtldef_59	: STD_LOGIC;
  SIGNAL rtldef_58	: STD_LOGIC;
  SIGNAL rtldef_57	: STD_LOGIC;
  SIGNAL rtldef_56	: STD_LOGIC;
  SIGNAL rtldef_55	: STD_LOGIC;
  SIGNAL rtldef_54	: STD_LOGIC;
  SIGNAL rtldef_53	: STD_LOGIC;
  SIGNAL rtldef_52	: STD_LOGIC;
  SIGNAL rtldef_51	: STD_LOGIC;
  SIGNAL rtldef_50	: STD_LOGIC;
  SIGNAL rtldef_49	: STD_LOGIC;
  SIGNAL rtldef_48	: STD_LOGIC;
  SIGNAL rtldef_47	: STD_LOGIC;
  SIGNAL rtldef_46	: STD_LOGIC;
  SIGNAL rtldef_45	: STD_LOGIC;
  SIGNAL rtldef_44	: STD_LOGIC;
  SIGNAL rtldef_43	: STD_LOGIC;
  SIGNAL rtldef_42	: STD_LOGIC;
  SIGNAL rtldef_41	: STD_LOGIC;
  SIGNAL rtldef_40	: STD_LOGIC;
  SIGNAL rtldef_39	: STD_LOGIC;
  SIGNAL rtldef_38	: STD_LOGIC;
  SIGNAL rtldef_37	: STD_LOGIC;
  SIGNAL rtldef_36	: STD_LOGIC;
  SIGNAL rtldef_35	: STD_LOGIC;
  SIGNAL rtldef_34	: STD_LOGIC;
  SIGNAL rtldef_33	: STD_LOGIC;
  SIGNAL rtldef_32	: STD_LOGIC;
  SIGNAL rtldef_31	: STD_LOGIC;
  SIGNAL rtldef_30	: STD_LOGIC;
  SIGNAL rtldef_29	: STD_LOGIC;
  SIGNAL rtldef_28	: STD_LOGIC;
  SIGNAL rtldef_27	: STD_LOGIC;
  SIGNAL rtldef_26	: STD_LOGIC;
  SIGNAL rtldef_25	: STD_LOGIC;
  SIGNAL rtldef_24	: STD_LOGIC;
  SIGNAL rtldef_23	: STD_LOGIC;
  SIGNAL rtldef_22	: STD_LOGIC;
  SIGNAL rtldef_21	: STD_LOGIC;
  SIGNAL rtldef_20	: STD_LOGIC;
  SIGNAL rtldef_19	: STD_LOGIC;
  SIGNAL rtldef_18	: STD_LOGIC;
  SIGNAL rtldef_17	: STD_LOGIC;
  SIGNAL rtldef_16	: STD_LOGIC;
  SIGNAL rtldef_15	: STD_LOGIC;
  SIGNAL rtldef_14	: STD_LOGIC;
  SIGNAL rtldef_13	: STD_LOGIC;
  SIGNAL rtldef_12	: STD_LOGIC;
  SIGNAL rtldef_11	: STD_LOGIC;
  SIGNAL rtldef_10	: STD_LOGIC;
  SIGNAL rtldef_9	: STD_LOGIC;
  SIGNAL rtldef_8	: STD_LOGIC;
  SIGNAL rtldef_7	: STD_LOGIC;
  SIGNAL rtldef_6	: STD_LOGIC;
  SIGNAL rtldef_5	: STD_LOGIC;
  SIGNAL rtldef_4	: STD_LOGIC;
  SIGNAL rtldef_3	: STD_LOGIC;
  SIGNAL rtldef_2	: STD_LOGIC;
  SIGNAL rtldef_1	: STD_LOGIC;
  SIGNAL rtldef_0	: STD_LOGIC;
  SIGNAL decaltampon_s	: STD_LOGIC_VECTOR(31 DOWNTO 0);
  SIGNAL shiftval_s	: UNSIGNED(30 DOWNTO 0);
  SIGNAL etg1	: UNSIGNED(30 DOWNTO 0);
  SIGNAL etg2	: UNSIGNED(30 DOWNTO 0);
  SIGNAL etg3	: UNSIGNED(30 DOWNTO 0);
  SIGNAL etg4	: UNSIGNED(30 DOWNTO 0);
  SIGNAL etg5	: UNSIGNED(30 DOWNTO 0);
  SIGNAL p72_8_reddef_73	: UNSIGNED(4 DOWNTO 0);
  SIGNAL p72_8_def_1	: BOOLEAN;
  SIGNAL p72_8_def_0	: BOOLEAN;

BEGIN
  rtl_unsigned_13 <= unsigned'("0000000000000000000000000000000");
  rtl_unsigned_12 <= unsigned'("0000000000000000000000000000001");
  rtl_unsigned_11 <= unsigned'("0000000000000000000000000000000");
  rtl_unsigned_10 <= unsigned'("0000000000000000000000000000010");
  rtl_unsigned_9 <= unsigned'("0000000000000000000000000000000");
  rtl_unsigned_8 <= unsigned'("0000000000000000000000000000100");
  rtl_unsigned_7 <= unsigned'("0000000000000000000000000000000");
  rtl_unsigned_6 <= unsigned'("0000000000000000000000000001000");
  rtl_unsigned_5 <= unsigned'("0000000000000000000000000000000");
  rtl_unsigned_4 <= unsigned'("0000000000000000000000000010000");
  rtl_unsigned_3 <= unsigned(rtlexts_1);
  rtl_unsigned_2 <= unsigned'("11111");
  rtl_signed_1 <= signed(rtl_std_logic_vector_0);
  rtl_std_logic_vector_0 <= (shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4)
 & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4)
 & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4)
 & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4) & shift_val(4)
 & shift_val(4) & shift_val(4) & shift_val);
  rtlexts_1 <= rtl_signed_1;
  rtlexts_0 <= shiftval_s(4 downto 0);
  rtldef_68 <= '1' WHEN p72_8_def_0 ELSE
     '0';
  rtldef_67 <= '1' WHEN NOT(p72_8_def_0) ELSE
     '0';
  cout <= ((rtldef_67 AND ((rtldef_65 AND (rtldef_64 AND din(0))) OR (rtldef_66 AND ((rtldef_32
 AND din(31)) OR ((rtldef_33 AND din(30)) OR ((rtldef_34 AND din(29)) OR ((rtldef_35
 AND din(28)) OR ((rtldef_36 AND din(27)) OR ((rtldef_37 AND din(26)) OR ((rtldef_38
 AND din(25)) OR ((rtldef_39 AND din(24)) OR ((rtldef_40 AND din(23)) OR ((rtldef_41
 AND din(22)) OR ((rtldef_42 AND din(21)) OR ((rtldef_43 AND din(20)) OR ((rtldef_44
 AND din(19)) OR ((rtldef_45 AND din(18)) OR ((rtldef_46 AND din(17)) OR ((rtldef_47
 AND din(16)) OR ((rtldef_48 AND din(15)) OR ((rtldef_49 AND din(14)) OR ((rtldef_50
 AND din(13)) OR ((rtldef_51 AND din(12)) OR ((rtldef_52 AND din(11)) OR ((rtldef_53
 AND din(10)) OR ((rtldef_54 AND din(9)) OR ((rtldef_55 AND din(8)) OR ((rtldef_56
 AND din(7)) OR ((rtldef_57 AND din(6)) OR ((rtldef_58 AND din(5)) OR ((rtldef_59
 AND din(4)) OR ((rtldef_60 AND din(3)) OR ((rtldef_61 AND din(2)) OR ((rtldef_62
 AND din(1)) OR (rtldef_63 AND din(0)))))))))))))))))))))))))))))))))))) OR (rtldef_68
 AND ((rtldef_0 AND din(31)) OR ((rtldef_1 AND din(30)) OR ((rtldef_2 AND din(29)
) OR ((rtldef_3 AND din(28)) OR ((rtldef_4 AND din(27)) OR ((rtldef_5 AND din(26)
) OR ((rtldef_6 AND din(25)) OR ((rtldef_7 AND din(24)) OR ((rtldef_8 AND din(23)
) OR ((rtldef_9 AND din(22)) OR ((rtldef_10 AND din(21)) OR ((rtldef_11 AND din(20)
) OR ((rtldef_12 AND din(19)) OR ((rtldef_13 AND din(18)) OR ((rtldef_14 AND din(17)
) OR ((rtldef_15 AND din(16)) OR ((rtldef_16 AND din(15)) OR ((rtldef_17 AND din(14)
) OR ((rtldef_18 AND din(13)) OR ((rtldef_19 AND din(12)) OR ((rtldef_20 AND din(11)
) OR ((rtldef_21 AND din(10)) OR ((rtldef_22 AND din(9)) OR ((rtldef_23 AND din(8)
) OR ((rtldef_24 AND din(7)) OR ((rtldef_25 AND din(6)) OR ((rtldef_26 AND din(5)
) OR ((rtldef_27 AND din(4)) OR ((rtldef_28 AND din(3)) OR ((rtldef_29 AND din(2)
) OR ((rtldef_30 AND din(1)) OR (rtldef_31 AND din(0))))))))))))))))))))))))))))
)))))));
  rtldef_66 <= '1' WHEN p72_8_def_1 ELSE
     '0';
  rtldef_65 <= '1' WHEN NOT(p72_8_def_1) ELSE
     '0';
  rtldef_64 <= '1' WHEN (shift_rrx = '1') ELSE
     '0';
  rtldef_63 <= '1' WHEN (shiftval_s = "0000000000000000000000000000000") ELSE
     '0';
  rtldef_62 <= '1' WHEN (shiftval_s = "0000000000000000000000000011111") ELSE
     '0';
  rtldef_61 <= '1' WHEN (shiftval_s = "0000000000000000000000000011110") ELSE
     '0';
  rtldef_60 <= '1' WHEN (shiftval_s = "0000000000000000000000000011101") ELSE
     '0';
  rtldef_59 <= '1' WHEN (shiftval_s = "0000000000000000000000000011100") ELSE
     '0';
  rtldef_58 <= '1' WHEN (shiftval_s = "0000000000000000000000000011011") ELSE
     '0';
  rtldef_57 <= '1' WHEN (shiftval_s = "0000000000000000000000000011010") ELSE
     '0';
  rtldef_56 <= '1' WHEN (shiftval_s = "0000000000000000000000000011001") ELSE
     '0';
  rtldef_55 <= '1' WHEN (shiftval_s = "0000000000000000000000000011000") ELSE
     '0';
  rtldef_54 <= '1' WHEN (shiftval_s = "0000000000000000000000000010111") ELSE
     '0';
  rtldef_53 <= '1' WHEN (shiftval_s = "0000000000000000000000000010110") ELSE
     '0';
  rtldef_52 <= '1' WHEN (shiftval_s = "0000000000000000000000000010101") ELSE
     '0';
  rtldef_51 <= '1' WHEN (shiftval_s = "0000000000000000000000000010100") ELSE
     '0';
  rtldef_50 <= '1' WHEN (shiftval_s = "0000000000000000000000000010011") ELSE
     '0';
  rtldef_49 <= '1' WHEN (shiftval_s = "0000000000000000000000000010010") ELSE
     '0';
  rtldef_48 <= '1' WHEN (shiftval_s = "0000000000000000000000000010001") ELSE
     '0';
  rtldef_47 <= '1' WHEN (shiftval_s = "0000000000000000000000000010000") ELSE
     '0';
  rtldef_46 <= '1' WHEN (shiftval_s = "0000000000000000000000000001111") ELSE
     '0';
  rtldef_45 <= '1' WHEN (shiftval_s = "0000000000000000000000000001110") ELSE
     '0';
  rtldef_44 <= '1' WHEN (shiftval_s = "0000000000000000000000000001101") ELSE
     '0';
  rtldef_43 <= '1' WHEN (shiftval_s = "0000000000000000000000000001100") ELSE
     '0';
  rtldef_42 <= '1' WHEN (shiftval_s = "0000000000000000000000000001011") ELSE
     '0';
  rtldef_41 <= '1' WHEN (shiftval_s = "0000000000000000000000000001010") ELSE
     '0';
  rtldef_40 <= '1' WHEN (shiftval_s = "0000000000000000000000000001001") ELSE
     '0';
  rtldef_39 <= '1' WHEN (shiftval_s = "0000000000000000000000000001000") ELSE
     '0';
  rtldef_38 <= '1' WHEN (shiftval_s = "0000000000000000000000000000111") ELSE
     '0';
  rtldef_37 <= '1' WHEN (shiftval_s = "0000000000000000000000000000110") ELSE
     '0';
  rtldef_36 <= '1' WHEN (shiftval_s = "0000000000000000000000000000101") ELSE
     '0';
  rtldef_35 <= '1' WHEN (shiftval_s = "0000000000000000000000000000100") ELSE
     '0';
  rtldef_34 <= '1' WHEN (shiftval_s = "0000000000000000000000000000011") ELSE
     '0';
  rtldef_33 <= '1' WHEN (shiftval_s = "0000000000000000000000000000010") ELSE
     '0';
  rtldef_32 <= '1' WHEN (shiftval_s = "0000000000000000000000000000001") ELSE
     '0';
  p72_8_def_1 <= (((shift_lsr = '1') OR (shift_asr = '1')) OR (shift_ror = '1'));
  rtldef_31 <= '1' WHEN (p72_8_reddef_73 = "00000") ELSE
     '0';
  rtldef_30 <= '1' WHEN (p72_8_reddef_73 = "11111") ELSE
     '0';
  rtldef_29 <= '1' WHEN (p72_8_reddef_73 = "11110") ELSE
     '0';
  rtldef_28 <= '1' WHEN (p72_8_reddef_73 = "11101") ELSE
     '0';
  rtldef_27 <= '1' WHEN (p72_8_reddef_73 = "11100") ELSE
     '0';
  rtldef_26 <= '1' WHEN (p72_8_reddef_73 = "11011") ELSE
     '0';
  rtldef_25 <= '1' WHEN (p72_8_reddef_73 = "11010") ELSE
     '0';
  rtldef_24 <= '1' WHEN (p72_8_reddef_73 = "11001") ELSE
     '0';
  rtldef_23 <= '1' WHEN (p72_8_reddef_73 = "11000") ELSE
     '0';
  rtldef_22 <= '1' WHEN (p72_8_reddef_73 = "10111") ELSE
     '0';
  rtldef_21 <= '1' WHEN (p72_8_reddef_73 = "10110") ELSE
     '0';
  rtldef_20 <= '1' WHEN (p72_8_reddef_73 = "10101") ELSE
     '0';
  rtldef_19 <= '1' WHEN (p72_8_reddef_73 = "10100") ELSE
     '0';
  rtldef_18 <= '1' WHEN (p72_8_reddef_73 = "10011") ELSE
     '0';
  rtldef_17 <= '1' WHEN (p72_8_reddef_73 = "10010") ELSE
     '0';
  rtldef_16 <= '1' WHEN (p72_8_reddef_73 = "10001") ELSE
     '0';
  rtldef_15 <= '1' WHEN (p72_8_reddef_73 = "10000") ELSE
     '0';
  rtldef_14 <= '1' WHEN (p72_8_reddef_73 = "01111") ELSE
     '0';
  rtldef_13 <= '1' WHEN (p72_8_reddef_73 = "01110") ELSE
     '0';
  rtldef_12 <= '1' WHEN (p72_8_reddef_73 = "01101") ELSE
     '0';
  rtldef_11 <= '1' WHEN (p72_8_reddef_73 = "01100") ELSE
     '0';
  rtldef_10 <= '1' WHEN (p72_8_reddef_73 = "01011") ELSE
     '0';
  rtldef_9 <= '1' WHEN (p72_8_reddef_73 = "01010") ELSE
     '0';
  rtldef_8 <= '1' WHEN (p72_8_reddef_73 = "01001") ELSE
     '0';
  rtldef_7 <= '1' WHEN (p72_8_reddef_73 = "01000") ELSE
     '0';
  rtldef_6 <= '1' WHEN (p72_8_reddef_73 = "00111") ELSE
     '0';
  rtldef_5 <= '1' WHEN (p72_8_reddef_73 = "00110") ELSE
     '0';
  rtldef_4 <= '1' WHEN (p72_8_reddef_73 = "00101") ELSE
     '0';
  rtldef_3 <= '1' WHEN (p72_8_reddef_73 = "00100") ELSE
     '0';
  rtldef_2 <= '1' WHEN (p72_8_reddef_73 = "00011") ELSE
     '0';
  rtldef_1 <= '1' WHEN (p72_8_reddef_73 = "00010") ELSE
     '0';
  rtldef_0 <= '1' WHEN (p72_8_reddef_73 = "00001") ELSE
     '0';
  p72_8_reddef_73 <= (rtl_unsigned_2 - rtlexts_0);
  p72_8_def_0 <= (shift_lsl = '1');
  decaltampon_s <= "11111111111111111111111111111111" WHEN ((din(31) = '1') AND (shift_asr = '1')) ELSE
     "00000000000000000000000000000000";
  shiftval_s <= rtl_unsigned_3;
  etg5 <= rtl_unsigned_4 WHEN (shift_val(4) = '1') ELSE
     rtl_unsigned_5;
  etg4 <= rtl_unsigned_6 WHEN (shift_val(3) = '1') ELSE
     rtl_unsigned_7;
  etg3 <= rtl_unsigned_8 WHEN (shift_val(2) = '1') ELSE
     rtl_unsigned_9;
  etg2 <= rtl_unsigned_10 WHEN (shift_val(1) = '1') ELSE
     rtl_unsigned_11;
  etg1 <= rtl_unsigned_12 WHEN (shift_val(0) = '1') ELSE
     rtl_unsigned_13;
END RTL;
